import type { NextPage } from "next"
import Head from "next/head"
import NextComponent from "../src/components/Next"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextComponent styles={styles} />
    </div>
  )
}

export default Home
